from __future__ import annotations

import hashlib
import json
import re
import unicodedata
from dataclasses import dataclass
from difflib import SequenceMatcher
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

_REASON_ORDER = {
    "exact_title": 0,
    "exact_original_title": 1,
    "exact_en_title": 2,
    "exact_alias": 3,
    "token_set_exact": 4,
    "no_query": 5,
    "no_match": 6,
    "year_match": 10,
    "episodic_tv": 20,
    "cross_source_corroboration": 30,
    "auto_threshold_met": 40,
    "review_needed": 41,
    "needs_manual_review": 42,
    "short_title_risk": 50,
    "score_too_low": 60,
    "all_rejected": 70,
    "no_candidates": 71,
}


def _ordered_reasons(items: Sequence[str]) -> Tuple[str, ...]:
    unique = list(dict.fromkeys(items))
    return tuple(
        sorted(
            unique,
            key=lambda value: (_REASON_ORDER.get(value, 999), value),
        )
    )

# Bump this whenever parsing changes so cached search results cannot retain
# query terms generated by an older parser.
PARSER_SCHEMA_VERSION = "3"
SCORER_SCHEMA_VERSION = "1"

MANUAL_TARGET_LIBRARIES = ("tv", "movie", "children")
_MANUAL_NAME_INVALID_RE = re.compile(r'[\\/:*?"<>|\x00-\x1f\x7f-\x9f]')
_MANUAL_FORMAT_INVALID_CHARS = frozenset(
    "\u061c\u200e\u200f\u202a\u202b\u202c\u202d\u202e\u2066\u2067\u2068\u2069"
)
_MANUAL_NAME_MAX_BYTES = 160


def validate_manual_name(value: object) -> Tuple[bool, str]:
    """Validate a user supplied directory name without silently rewriting it."""
    if (
        not isinstance(value, str)
        or not value
        or value != value.strip()
        or len(value.splitlines()) != 1
    ):
        return False, "invalid_manual_name"
    try:
        encoded = value.encode("utf-8", "strict")
    except UnicodeEncodeError:
        return False, "invalid_manual_name"
    if len(encoded) > _MANUAL_NAME_MAX_BYTES or value in {".", ".."}:
        return False, "invalid_manual_name"
    if _MANUAL_NAME_INVALID_RE.search(value) or any(
        char in _MANUAL_FORMAT_INVALID_CHARS for char in value
    ):
        return False, "invalid_manual_name"
    return True, ""


def _normalize_whitespace(value: str) -> str:
    return re.sub(r"\s+", " ", unicodedata.normalize("NFKC", str(value))).strip()


def validate_manual_raw_title(value: object) -> Tuple[bool, str]:
    """Validate an exact preview-row key without normalizing its spelling."""
    if not isinstance(value, str) or not value or not value.strip() or len(value) > 255:
        return False, "invalid_raw_title"
    try:
        value.encode("utf-8", "strict")
    except UnicodeEncodeError:
        return False, "invalid_raw_title"
    if any(char in value for char in ("\x00", "=>")):
        return False, "invalid_raw_title"
    if len(value.splitlines()) != 1:
        return False, "invalid_raw_title"
    if any(ord(char) < 0x20 or 0x7F <= ord(char) <= 0x9F for char in value):
        return False, "invalid_raw_title"
    if any(char in value for char in ("\u2028", "\u2029")):
        return False, "invalid_raw_title"
    if any(char in _MANUAL_FORMAT_INVALID_CHARS for char in value):
        return False, "invalid_raw_title"
    return True, ""


def normalize_title(value: str) -> str:
    normalized = _normalize_whitespace(value)
    normalized = re.sub(
        r"[\s\-_.,/\\:;!！?？。；、，()（）\[\]{}<>【】«»“”‘’'\"|]",
        "",
        normalized,
    )
    return normalized.casefold()


def tokenize_title(value: str) -> Tuple[str, ...]:
    normalized = normalize_title(value)
    if not normalized:
        return ()
    latin = tuple(re.findall(r"[a-z0-9]+", normalized))
    cjk = tuple(re.findall(r"[\u4e00-\u9fff]+", normalized))
    bigrams: List[str] = []
    for chunk in cjk:
        for index in range(len(chunk) - 1):
            bigrams.append(chunk[index : index + 2])
    return tuple(sorted(set(latin + tuple(bigrams))))


def token_similarity(left: str, right: str) -> float:
    left_tokens = set(tokenize_title(left))
    right_tokens = set(tokenize_title(right))
    if not left_tokens and not right_tokens:
        return 0.0
    if not left_tokens or not right_tokens:
        return 0.0
    return len(left_tokens & right_tokens) / len(left_tokens | right_tokens)


@dataclass(frozen=True)
class QueryCandidate:
    text: str
    origin: str
    quality_bonus: int = 5


@dataclass(frozen=True)
class TitleHints:
    raw_title: str
    local_title: str
    year: Optional[int]
    season_hints: Tuple[int, ...]
    query_candidates: Tuple[QueryCandidate, ...]
    reason_codes: Tuple[str, ...]

    def to_dict(self) -> Dict[str, object]:
        return {
            "raw_title": self.raw_title,
            "local_title": self.local_title,
            "year": self.year,
            "season_hints": list(self.season_hints),
            "query_candidates": [
                {
                    "text": item.text,
                    "origin": item.origin,
                    "quality_bonus": item.quality_bonus,
                }
                for item in self.query_candidates
            ],
            "reason_codes": list(self.reason_codes),
        }

    @classmethod
    def from_dict(cls, value: Dict[str, object]) -> "TitleHints":
        return cls(
            raw_title=str(value.get("raw_title", "")),
            local_title=str(value.get("local_title", "")),
            year=value.get("year"),  # type: ignore[arg-type]
            season_hints=tuple(int(item) for item in value.get("season_hints", ())),
            query_candidates=tuple(
                QueryCandidate(
                    text=str(item["text"]),
                    origin=str(item["origin"]),
                    quality_bonus=int(item.get("quality_bonus", 5)),
                )
                for item in value.get("query_candidates", ())
                if isinstance(item, dict)
            ),
            reason_codes=tuple(str(item) for item in value.get("reason_codes", ())),
        )


@dataclass(frozen=True)
class ManualOverride:
    raw_title: str
    action: str
    value: str = ""
    target_library: str = ""
    source_revision: str = ""
    target_output_root: str = ""
    source_path: str = ""
    source_identity: Tuple[Tuple[str, int], ...] = ()
    source_snapshot_digest: str = ""
    source_manifest: Tuple[Tuple[str, int, int, int, int, int], ...] = ()
    source_manifest_digest: str = ""
    source_directory_manifest: Tuple[Tuple[str, int, int], ...] = ()
    source_directory_manifest_digest: str = ""


@dataclass(frozen=True)
class ManualOverrideResult:
    overrides: Tuple[ManualOverride, ...]
    errors: Tuple[str, ...]
    line_errors: Tuple[Tuple[str, str], ...] = ()


@dataclass(frozen=True)
class DirectoryHints:
    media_count: int
    seasons: Tuple[int, ...]
    episodic: bool

    def to_dict(self) -> Dict[str, object]:
        return {
            "media_count": self.media_count,
            "seasons": list(self.seasons),
            "episodic": self.episodic,
        }

    @classmethod
    def from_dict(cls, value: Dict[str, object]) -> "DirectoryHints":
        return cls(
            media_count=int(value.get("media_count", 0)),
            seasons=tuple(int(item) for item in value.get("seasons", ())),
            episodic=bool(value.get("episodic", False)),
        )


@dataclass(frozen=True)
class MetadataCandidate:
    key: str
    source: str
    media_id: str
    media_type: str
    title: str
    en_title: str = ""
    original_title: str = ""
    aliases: Tuple[str, ...] = ()
    year: Optional[int] = None
    detail_link: str = ""
    matched_query: str = ""
    query_origin: str = ""
    source_rank: int = 0

    def to_dict(self) -> Dict[str, object]:
        return {
            "key": self.key,
            "source": self.source,
            "media_id": self.media_id,
            "media_type": self.media_type,
            "title": self.title,
            "en_title": self.en_title,
            "original_title": self.original_title,
            "aliases": list(self.aliases),
            "year": self.year,
            "detail_link": self.detail_link,
            "matched_query": self.matched_query,
            "query_origin": self.query_origin,
            "source_rank": self.source_rank,
        }

    @classmethod
    def from_dict(cls, value: Dict[str, object]) -> "MetadataCandidate":
        return cls(
            key=str(value.get("key", "")),
            source=str(value.get("source", "")),
            media_id=str(value.get("media_id", "")),
            media_type=str(value.get("media_type", "")),
            title=str(value.get("title", "")),
            en_title=str(value.get("en_title", "")),
            original_title=str(value.get("original_title", "")),
            aliases=tuple(str(item) for item in value.get("aliases", ())),
            year=value.get("year"),  # type: ignore[arg-type]
            detail_link=str(value.get("detail_link", "")),
            matched_query=str(value.get("matched_query", "")),
            query_origin=str(value.get("query_origin", "")),
            source_rank=int(value.get("source_rank", 0)),
        )


@dataclass(frozen=True)
class ScoredCandidate:
    candidate: MetadataCandidate
    score: int
    reason_codes: Tuple[str, ...]
    rejected_reason: str = ""

    def to_dict(self) -> Dict[str, object]:
        return {
            "candidate": self.candidate.to_dict(),
            "score": self.score,
            "reason_codes": list(self.reason_codes),
            "rejected_reason": self.rejected_reason,
        }

    @classmethod
    def from_dict(cls, value: Dict[str, object]) -> "ScoredCandidate":
        return cls(
            candidate=MetadataCandidate.from_dict(value["candidate"]),
            score=int(value.get("score", 0)),
            reason_codes=tuple(value.get("reason_codes", ())),
            rejected_reason=str(value.get("rejected_reason", "")),
        )


@dataclass(frozen=True)
class MatchEvaluation:
    status: str
    top: Optional[ScoredCandidate]
    eligible: Tuple[ScoredCandidate, ...]
    margin: int
    reason_codes: Tuple[str, ...]


def _to_int(value: str) -> Optional[int]:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _parse_year(raw: str) -> Optional[int]:
    match = re.search(r"(?:\(|（)(\d{4})(?:\)|）)", raw)
    if not match:
        return None
    return _to_int(match.group(1))


def _strip_year(raw: str) -> str:
    return re.sub(r"(?:\(|（)\d{4}(?:\)|）)", "", raw).strip()


_CHINESE_NUM_MAP = {
    "零": 0,
    "一": 1,
    "二": 2,
    "三": 3,
    "四": 4,
    "五": 5,
    "六": 6,
    "七": 7,
    "八": 8,
    "九": 9,
    "十": 10,
}


def _parse_chinese_number(raw: str) -> Optional[int]:
    if not raw:
        return None
    if raw.isdigit():
        return _to_int(raw)
    if "十" in raw:
        if raw == "十":
            return 10
        prefix, suffix = raw.split("十", 1)
        if prefix and prefix not in _CHINESE_NUM_MAP:
            return None
        tens = 1 if prefix == "" else _CHINESE_NUM_MAP.get(prefix, 0)
        ones = _CHINESE_NUM_MAP.get(suffix, 0) if suffix else 0
        return tens * 10 + ones
    total = 0
    for char in raw:
        value = _CHINESE_NUM_MAP.get(char)
        if value is None:
            return None
        total += value
    return total or None


_SEASON_NUMBER = r"[0-9零一二三四五六七八九十]+"
_SEASON_RANGE_SEPARATOR = r"(?:[-~～－—–/／]|到|至)"


def _add_season_range(seasons: set, start: Optional[int], end: Optional[int]) -> None:
    """Add a plausible season range without expanding arbitrary large numbers."""
    if start is None or end is None or start < 1 or end < start:
        return
    # Course collections normally use a small, contiguous range.  A bound
    # avoids accidentally treating a video frame range as hundreds of seasons.
    if end > 99 or end - start > 49:
        return
    seasons.update(range(start, end + 1))


def _extract_seasons(value: str) -> Tuple[int, ...]:
    seasons = set()
    # Accept both “第1-8季” and common bare collection forms such as
    # “1-8季” / “1～8季” / “1到8季”.  The trailing 季 keeps ordinary
    # numeric text from being interpreted as a season range.
    for match in re.finditer(
        rf"(?:第\s*)?({_SEASON_NUMBER})\s*{_SEASON_RANGE_SEPARATOR}\s*(?:第\s*)?({_SEASON_NUMBER})\s*季",
        value,
    ):
        _add_season_range(
            seasons,
            _parse_chinese_number(match.group(1)),
            _parse_chinese_number(match.group(2)),
        )
    for match in re.finditer(
        rf"(?i)\bS?\s*0*([0-9]{{1,3}})\s*{_SEASON_RANGE_SEPARATOR}\s*S?\s*0*([0-9]{{1,3}})\b",
        value,
    ):
        _add_season_range(seasons, _to_int(match.group(1)), _to_int(match.group(2)))
    for match in re.finditer(r"第\s*([0-9零一二三四五六七八九十]+)\s*季", value):
        season = _parse_chinese_number(match.group(1))
        if season is not None:
            seasons.add(season)
    for match in re.finditer(r"(?i)\bS\s*0*([0-9]{1,3})\b", value):
        value_int = _to_int(match.group(1))
        if value_int:
            seasons.add(value_int)
    for match in re.finditer(r"(?i)\bSeason\s*0*([0-9]{1,3})\b", value):
        value_int = _to_int(match.group(1))
        if value_int:
            seasons.add(value_int)
    return tuple(sorted(seasons))


def _strip_season_markers(value: str) -> str:
    text = re.sub(
        rf"(?i)\bS\s*0*([0-9]{{1,3}})\s*{_SEASON_RANGE_SEPARATOR}\s*S?\s*0*([0-9]{{1,3}})\b",
        "",
        value,
    )
    text = re.sub(r"(?i)\bS\s*0*([0-9]{1,3})\b", "", text)
    text = re.sub(
        rf"(?i)\bseason\s*0*([0-9]{{1,3}})\s*{_SEASON_RANGE_SEPARATOR}\s*[0-9]{{1,3}}\b",
        "",
        text,
    )
    text = re.sub(r"(?i)\bseason\s*0*([0-9]{1,3})\b", "", text)
    text = re.sub(
        rf"(?:第\s*)?{_SEASON_NUMBER}\s*{_SEASON_RANGE_SEPARATOR}\s*(?:第\s*)?{_SEASON_NUMBER}\s*季",
        "",
        text,
    )
    text = re.sub(r"第\s*[0-9零一二三四五六七八九十]+\s*[季集]\s*", "", text)
    return re.sub(r"\s{2,}", " ", text).strip()


def _strip_empty_brackets(value: str) -> str:
    cleaned = value
    while True:
        updated = re.sub(r"\s*(?:\(\s*\)|（\s*）|\[\s*\]|【\s*】)\s*", " ", cleaned)
        if updated == cleaned:
            break
        cleaned = updated
    return _normalize_whitespace(cleaned)


def _strip_technical_trailing_noise(value: str) -> str:
    """Remove only obvious trailing video/resolution markers from a folder name."""
    cleaned = _normalize_whitespace(value)
    patterns = (
        r"(?i)(?:[\s._\-—–]*)?(?:视频|video)\s*(?:4320|2160|1440|1080|720|576|480)p(?:\s*(?:hd|uhd|hdr|web[- ]?dl|webrip|bluray|x26[45]|h\.?26[45]))*$",
        r"(?i)(?:[\s._\-—–]*)?(?:4320|2160|1440|1080|720|576|480)p(?:\s*(?:hd|uhd|hdr|web[- ]?dl|webrip|bluray|x26[45]|h\.?26[45]))*$",
        r"(?i)(?:[\s._\-—–]*)(?:web[- ]?dl|webrip|bluray|bdrip|hdtv)(?:\s*(?:x26[45]|h\.?26[45]|aac|hevc))?$",
    )
    for pattern in patterns:
        cleaned = re.sub(pattern, "", cleaned).strip()
    return _normalize_whitespace(cleaned)


def _strip_trailing_language_marker(value: str) -> str:
    cleaned = _normalize_whitespace(value)
    marker = (
        r"(?:中英双语(?:版)?|双语(?:版)?|中文(?:配音)?版|国语(?:配音)?版|"
        r"粤语(?:配音)?版|英语(?:配音)?版|日语(?:配音)?版|原声版|中字版)"
    )
    return _normalize_whitespace(re.sub(rf"(?:[\s._\-—–]*){marker}$", "", cleaned, flags=re.IGNORECASE))


def _strip_trailing_noise(value: str) -> str:
    cleaned = _normalize_whitespace(value)
    noise = ("高清修复版", "未删减", "全集", "合集", "抢先版", "主题")
    for marker in noise:
        cleaned = re.sub(
            rf"(?:(?<=^)|(?<=[\s,，。；;:：!！?？()\[\]【】《》])){re.escape(marker)}(?:(?=$)|(?=[\s,，。；;:：!！?？])|(?=[)\]】]))",
            "",
            cleaned,
        )
    cleaned = re.sub(r"\s{2,}", " ", cleaned).strip()
    return cleaned


def _strip_noise_tokens(value: str) -> str:
    cleaned = _normalize_whitespace(value)
    noise = ("高清修复版", "未删减", "全集", "合集", "抢先版", "未删")
    boundary = r"(?:(?<=^)|(?<=[\s,，。；;:：!！?？()\[\]【】《》]))"
    boundary_end = r"(?:(?=$)|(?=[\s,，。；;:：!！?？()\[\]【】]))"
    for marker in noise:
        cleaned = re.sub(
            rf"{boundary}{re.escape(marker)}{boundary_end}",
            "",
            cleaned,
        )
    return _normalize_whitespace(cleaned)


def _book_title(value: str) -> Optional[str]:
    match = re.search(r"《([^》]+)》", value)
    if not match:
        return None
    return _normalize_whitespace(match.group(1))


def _first_clause(value: str) -> str:
    for chunk in re.split(r"[，,：:；;|]", value):
        stripped = chunk.strip()
        if stripped:
            return stripped
    return value.strip()


def _latin_segments(value: str) -> Tuple[str, ...]:
    return tuple(s.strip() for s in re.findall(r"[A-Za-z][A-Za-z0-9 .&'+_-]*[A-Za-z0-9]", value) if s.strip())


def _cjk_segments(value: str) -> Tuple[str, ...]:
    segments: List[str] = []
    for match in re.finditer(r"[\u4e00-\u9fff]{2,}", value):
        segment = match.group(0).strip()
        if not segment:
            continue
        if segment[0].isdigit():
            continue
        if len(segment) > 8:
            continue
        if segment not in segments:
            segments.append(segment)
    return tuple(segments)


def _append_candidate(
    items: List[QueryCandidate], text: str, origin: str, bonus: int = 5
) -> None:
    normalized = normalize_title(text)
    if not normalized:
        return
    for existing in items:
        if normalize_title(existing.text) == normalized:
            return
    items.append(QueryCandidate(text=_normalize_whitespace(text), origin=origin, quality_bonus=bonus))


def parse_title(raw_title: str, manual_query: Optional[str] = None) -> TitleHints:
    raw = _normalize_whitespace(raw_title)
    reason_codes: List[str] = []
    year = _parse_year(raw)
    if year is None:
        reason_codes.append("no_year")
    else:
        reason_codes.append("year")

    body = _strip_year(raw)
    seasons = _extract_seasons(body)
    body = _strip_season_markers(body)
    body = _strip_technical_trailing_noise(body)
    body = _strip_empty_brackets(body)
    body = _strip_trailing_language_marker(body)
    body = _strip_empty_brackets(body)
    body = _strip_noise_tokens(body)
    body = _strip_trailing_noise(body)

    primary = _book_title(body)
    local = _strip_trailing_noise(primary or _first_clause(body))
    local = _strip_trailing_noise(_strip_season_markers(local))
    local = _strip_technical_trailing_noise(local)
    local = _strip_empty_brackets(local)
    local = _strip_trailing_language_marker(local)
    local = _strip_empty_brackets(local)
    if not local:
        reason_codes.append("empty_local")
        local = "Course"

    query_candidates: List[QueryCandidate] = []
    if manual_query:
        _append_candidate(query_candidates, _strip_trailing_noise(_strip_season_markers(manual_query)), "manual")

    if primary:
        _append_candidate(query_candidates, primary, "book_title")

    _append_candidate(query_candidates, local, "first_clause")

    source_text = primary or local
    for item in _latin_segments(source_text):
        _append_candidate(query_candidates, item, "latin_segment")
    for item in _cjk_segments(source_text):
        _append_candidate(query_candidates, item, "cjk_segment")

    return TitleHints(
        raw_title=raw,
        local_title=local,
        year=year,
        season_hints=seasons,
        query_candidates=tuple(query_candidates[:3]),
        reason_codes=tuple(reason_codes),
    )


def parse_manual_overrides(
    raw_text: str, target_libraries: Optional[Iterable[str]] = None
) -> ManualOverrideResult:
    if not isinstance(raw_text, str):
        return ManualOverrideResult(
            (),
            ("invalid_manual_overrides_text",),
            (("", "invalid_manual_overrides_text"),),
        )

    overrides: List[ManualOverride] = []
    seen: Dict[str, ManualOverride] = {}
    errors: List[str] = []
    line_errors: List[Tuple[str, str]] = []
    allowed_targets = (
        {
            str(target).strip().lower()
            for target in target_libraries
            if str(target).strip()
        }
        if target_libraries is not None
        else set(MANUAL_TARGET_LIBRARIES)
    )

    for line in raw_text.splitlines():
        text = line.strip()
        if not text:
            continue
        match = re.match(r"(?P<left>.*?)\s*=>\s*(?P<action>[a-zA-Z_]+)(?:\s*:\s*(?P<value>.*))?\s*$", text)
        if not match:
            errors.append(f"invalid_rule:{text}")
            line_errors.append(("", f"invalid_rule:{text}"))
            continue
        left = _normalize_whitespace(match.group("left"))
        action = match.group("action").strip().lower()
        value = (match.group("value") or "").strip()
        if not left:
            errors.append(f"empty_left:{text}")
            line_errors.append(("", f"empty_left:{text}"))
            continue
        if "=>" in left or "\x00" in left or "\r" in left or "\n" in left:
            errors.append(f"invalid_rule:{text}")
            line_errors.append((left, f"invalid_rule:{text}"))
            continue
        if action not in {"local", "query", "candidate", "ignore", "confirm"}:
            errors.append(f"invalid_rule:{text}")
            line_errors.append((left, f"invalid_rule:{text}"))
            continue

        if action == "ignore":
            if value:
                errors.append(f"invalid_ignore_rule:{text}")
                line_errors.append((left, f"invalid_ignore_rule:{text}"))
                continue
            if left in seen:
                errors.append(f"duplicate_left:{left}")
                line_errors.append((left, f"duplicate_left:{left}"))
                continue
            seen[left] = ManualOverride(left, "ignore")
            continue

        if action == "confirm":
            target, separator, final_name = value.partition(":")
            target_clean = target.strip().lower()
            if (
                not separator
                or target != target.strip()
                or target_clean != target
                or final_name != final_name.strip()
            ):
                error = f"invalid_confirm:{text}"
                errors.append(error)
                line_errors.append((left, error))
                continue
            valid_name, name_error = validate_manual_name(final_name)
            if target_clean not in allowed_targets or not valid_name:
                error = f"invalid_confirm:{text}"
                errors.append(error)
                line_errors.append((left, error if valid_name else name_error))
                continue
            if left in seen:
                errors.append(f"duplicate_left:{left}")
                line_errors.append((left, f"duplicate_left:{left}"))
                continue
            seen[left] = ManualOverride(left, "confirm", final_name, target_clean)
            continue

        if not value:
            errors.append(f"invalid_{action}:{text}")
            line_errors.append((left, f"invalid_{action}:{text}"))
            continue

        if action == "candidate":
            parts = tuple(_normalize_whitespace(part) for part in value.split(":"))
            if len(parts) != 3:
                errors.append(f"invalid_candidate:{text}")
                line_errors.append((left, f"invalid_candidate:{text}"))
                continue
            source, media_id, media_type = parts
            if source not in {"themoviedb", "douban"}:
                errors.append(f"invalid_candidate_source:{text}")
                line_errors.append((left, f"invalid_candidate_source:{text}"))
                continue
            if not media_id:
                errors.append(f"invalid_candidate_id:{text}")
                line_errors.append((left, f"invalid_candidate_id:{text}"))
                continue
            if media_type not in {"movie", "tv", "unknown"}:
                errors.append(f"invalid_candidate_type:{text}")
                line_errors.append((left, f"invalid_candidate_type:{text}"))
                continue
            value = f"{source}:{media_id}:{media_type}"

        if left in seen:
            errors.append(f"duplicate_left:{left}")
            line_errors.append((left, f"duplicate_left:{left}"))
            continue
        seen[left] = ManualOverride(raw_title=left, action=action, value=value)

    overrides.extend(seen.values())
    return ManualOverrideResult(
        overrides=tuple(overrides),
        errors=tuple(errors),
        line_errors=tuple((left, code) for left, code in line_errors),
    )


def query_hash(raw_title: str, queries: Sequence[QueryCandidate], sources: Sequence[str], provider_schema: str = "1") -> str:
    material = {
        "raw_title": raw_title,
        "queries": [q.text for q in queries],
        "query_origins": [q.origin for q in queries],
        "sources": list(sources),
        "parser_schema": PARSER_SCHEMA_VERSION,
        "provider_schema": provider_schema,
    }
    payload = json.dumps(material, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def decision_hash(
    directory_hints: DirectoryHints,
    auto_threshold: int,
    min_margin: int,
    append_tmdb_id: bool,
    uncertain_policy: str = "local",
) -> str:
    material = {
        "media_count": directory_hints.media_count,
        "seasons": list(directory_hints.seasons),
        "episodic": directory_hints.episodic,
        "auto_threshold": auto_threshold,
        "min_margin": min_margin,
        "append_tmdb_id": append_tmdb_id,
        "uncertain_policy": uncertain_policy,
        "schema": SCORER_SCHEMA_VERSION,
    }
    payload = json.dumps(material, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _candidate_names(candidate: MetadataCandidate) -> Tuple[str, ...]:
    names = [candidate.title, candidate.en_title, candidate.original_title]
    names.extend(candidate.aliases)
    return tuple(name for name in names if name)


def _aliases_signature(candidate: MetadataCandidate) -> set[str]:
    signatures: set[str] = set()
    for name in _candidate_names(candidate):
        normalized = normalize_title(name)
        if normalized:
            signatures.add(normalized)
    return signatures


def _cross_source_corroboration(items: Sequence[ScoredCandidate]) -> bool:
    if len(items) < 2:
        return False
    sources = {item.candidate.source for item in items}
    if not {"themoviedb", "douban"} <= sources:
        return False
    years = {item.candidate.year for item in items}
    if len(years) != 1 or None in years:
        return False
    base = _aliases_signature(items[0].candidate)
    for item in items[1:]:
        if not (base & _aliases_signature(item.candidate)):
            return False
    return True


def _hard_reject(hints: TitleHints, candidate: MetadataCandidate, directory: DirectoryHints) -> Optional[str]:
    if not _candidate_names(candidate):
        return "empty_title"
    if hints.year is not None and candidate.year is not None and hints.year != candidate.year:
        return "year_mismatch"
    if directory.episodic and candidate.media_type == "movie":
        return "episodic_movie"
    if not candidate.media_id:
        return "missing_source_id"
    return None


def _query_score(query: QueryCandidate, candidate: MetadataCandidate) -> Tuple[int, Optional[str]]:
    query_normalized = normalize_title(query.text)
    if not query_normalized:
        return 0, "no_query"
    exact_map = {
        "exact_title": candidate.title,
        "exact_original_title": candidate.original_title,
        "exact_en_title": candidate.en_title,
    }
    for key, title in exact_map.items():
        if normalize_title(title) == query_normalized:
            return 80, key

    for alias in _candidate_names(candidate):
        if normalize_title(alias) == query_normalized and alias not in (
            candidate.title,
            candidate.en_title,
            candidate.original_title,
        ):
            return 76, "exact_alias"

    query_tokens = set(tokenize_title(query.text))
    alias_tokens = {token for alias in _candidate_names(candidate) for token in tokenize_title(alias)}
    if query_tokens and query_tokens == alias_tokens:
        return 72, "token_set_exact"

    score = 0.0
    for alias in _candidate_names(candidate):
        alias_normalized = normalize_title(alias)
        if not alias_normalized:
            continue
        score = max(score, SequenceMatcher(None, query_normalized, alias_normalized).ratio())
        score = max(score, token_similarity(query.text, alias))
    if score <= 0.0:
        return 0, "no_match"
    return round(65 * score), None


def score_candidates(
    hints: TitleHints, directory: DirectoryHints, candidates: Sequence[MetadataCandidate]
) -> Tuple[ScoredCandidate, ...]:
    scored: List[ScoredCandidate] = []
    for candidate in candidates:
        rejected = _hard_reject(hints, candidate, directory)
        best = 0
        reasons: List[str] = []
        for query in hints.query_candidates:
            base, reason = _query_score(query, candidate)
            if reason:
                reasons.append(reason)
            score = base + query.quality_bonus
            if score > best:
                best = score

        if hints.year is not None and candidate.year == hints.year:
            reasons.append("year_match")
            best += 10
        if directory.episodic and candidate.media_type == "tv":
            reasons.append("episodic_tv")
            best += 8
        best = max(0, min(100, best))

        scored.append(
            ScoredCandidate(
                candidate=candidate,
                score=best,
                reason_codes=_ordered_reasons(reasons),
                rejected_reason=rejected or "",
            )
        )
    return tuple(scored)


def _cluster_candidates(candidates: Sequence[ScoredCandidate]) -> List[List[int]]:
    if not candidates:
        return []
    parent = list(range(len(candidates)))

    def find(index: int) -> int:
        while parent[index] != index:
            parent[index] = parent[parent[index]]
            index = parent[index]
        return index

    def union(left: int, right: int) -> None:
        left_root = find(left)
        right_root = find(right)
        if left_root != right_root:
            parent[right_root] = left_root

    for left_index, left_item in enumerate(candidates):
        left = left_item.candidate
        left_sig = _aliases_signature(left)
        for right_index in range(left_index + 1, len(candidates)):
            right = candidates[right_index].candidate
            if left.media_type != right.media_type:
                continue
            if left.year != right.year or left.year is None:
                continue
            if not (left_sig & _aliases_signature(right)):
                continue
            union(left_index, right_index)

    groups: Dict[int, List[int]] = {}
    for index in range(len(candidates)):
        groups.setdefault(find(index), []).append(index)
    return list(groups.values())


def evaluate_candidates(
    hints: TitleHints,
    directory: DirectoryHints,
    candidates: Sequence[MetadataCandidate],
    auto_threshold: int = 90,
    min_margin: int = 12,
) -> MatchEvaluation:
    scored = score_candidates(hints, directory, candidates)
    if not scored:
        return MatchEvaluation("local_fallback", None, (), 0, ("no_candidates",))

    eligible = tuple(item for item in scored if not item.rejected_reason)
    if not eligible:
        return MatchEvaluation("local_fallback", None, (), 0, ("all_rejected",))

    grouped_indexes = _cluster_candidates(eligible)
    grouped: List[Tuple[ScoredCandidate, List[ScoredCandidate]]] = []
    for group in grouped_indexes:
        members = [eligible[index] for index in group]
        members.sort(
            key=lambda item: (item.score, -item.candidate.source_rank),
            reverse=True,
        )
        top = members[0]
        cluster_reason = list(top.reason_codes)
        bonus = _cross_source_corroboration(members)
        if bonus:
            cluster_reason.append("cross_source_corroboration")
        grouped.append(
            (
                ScoredCandidate(
                    candidate=top.candidate,
                    score=min(100, top.score + (5 if bonus else 0)),
                    reason_codes=_ordered_reasons(cluster_reason),
                    rejected_reason=top.rejected_reason,
                ),
                members,
            )
        )

    grouped.sort(
        key=lambda item: (
            item[0].score,
            -item[0].candidate.source_rank,
        ),
        reverse=True,
    )
    ordered = tuple(item[0] for item in grouped)

    if not ordered:
        return MatchEvaluation("local_fallback", None, (), 0, ("all_rejected",))

    top = ordered[0]
    second_score = ordered[1].score if len(ordered) > 1 else 0
    margin = int(top.score - second_score)

    if top.score < 70:
        return MatchEvaluation("local_fallback", top, ordered, margin, ("score_too_low",))

    short_title = len(normalize_title(hints.local_title)) < 4
    if short_title:
        top_group = grouped[0][1]
        year_ok = hints.year is not None and top.candidate.year is not None and hints.year == top.candidate.year
        cross = _cross_source_corroboration(top_group)
        if not (year_ok or cross):
            return MatchEvaluation("review", top, ordered, margin, ("short_title_risk",))

    if top.score >= auto_threshold and margin >= min_margin:
        return MatchEvaluation("auto_external", top, ordered, margin, ("auto_threshold_met",))

    if top.score >= 70 and (top.score >= auto_threshold or margin >= min_margin):
        return MatchEvaluation("review", top, ordered, margin, ("review_needed",))

    return MatchEvaluation("review", top, ordered, margin, ("needs_manual_review",))


def _select_title_by_query(hints: TitleHints, candidate: MetadataCandidate) -> str:
    en_title = normalize_title(candidate.en_title)
    original_title = normalize_title(candidate.original_title)
    for query in hints.query_candidates:
        normalized = normalize_title(query.text)
        if normalized and normalized in {en_title, original_title}:
            return candidate.en_title or candidate.original_title
    return candidate.title or candidate.en_title or candidate.original_title


def format_root_name(hints: TitleHints, candidate: Optional[MetadataCandidate], append_tmdb_id: bool = False) -> str:
    if candidate is None:
        root = hints.local_title
        if hints.year is not None:
            root += f" ({hints.year})"
        return root

    base = _select_title_by_query(hints, candidate)
    root = base
    if candidate.year is not None:
        root += f" ({candidate.year})"
    if append_tmdb_id and candidate.source == "themoviedb":
        root += f" [tmdbid-{candidate.media_id}]"
    return root


def format_selected_candidate_name(
    candidate: MetadataCandidate, append_tmdb_id: bool = False
) -> str:
    """Format a manually selected result from the exact displayed provider title."""
    root = candidate.title or candidate.en_title or candidate.original_title
    if candidate.year is not None:
        root += f" ({candidate.year})"
    if append_tmdb_id and candidate.source == "themoviedb":
        root += f" [tmdbid-{candidate.media_id}]"
    return root


def format_file_prefix(candidate_title: str) -> str:
    base = _normalize_whitespace(candidate_title)
    base = re.sub(r"\s*\(\d{4}\)$", "", base).strip()
    base = re.sub(r"\s*\[tmdbid-[0-9]+\]\s*$", "", base, flags=re.IGNORECASE).strip()
    return base
